export const JUDETE = [
  'Alba', 'Arad', 'Argeș', 'Bacău', 'Bihor', 'Bistrița-Năsăud',
  'Botoșani', 'Brăila', 'Brașov', 'București', 'Buzău',
  'Caraș-Severin', 'Călărași', 'Cluj', 'Constanța', 'Covasna',
  'Dâmbovița', 'Dolj', 'Galați', 'Giurgiu', 'Gorj', 'Harghita',
  'Hunedoara', 'Ialomița', 'Iași', 'Ilfov', 'Maramureș', 'Mehedinți',
  'Mureș', 'Neamț', 'Olt', 'Prahova', 'Satu Mare', 'Sălaj',
  'Sibiu', 'Suceava', 'Teleorman', 'Timiș', 'Tulcea',
  'Vaslui', 'Vâlcea', 'Vrancea',
]

export const ORASE: Record<string, string[]> = {
  'Alba': ['Alba Iulia', 'Aiud', 'Blaj', 'Câmpeni', 'Cugir', 'Ocna Mureș', 'Sebeș', 'Teiuș', 'Zlatna'],
  'Arad': ['Arad', 'Chișineu-Criș', 'Curtici', 'Ineu', 'Lipova', 'Nădlac', 'Pâncota', 'Sântana', 'Sebiș'],
  'Argeș': ['Pitești', 'Câmpulung', 'Curtea de Argeș', 'Mioveni', 'Costești', 'Topoloveni', 'Ștefănești'],
  'Bacău': ['Bacău', 'Onești', 'Moinești', 'Comănești', 'Buhuși', 'Dărmănești', 'Slănic-Moldova', 'Târgu Ocna'],
  'Bihor': ['Oradea', 'Salonta', 'Beiuș', 'Marghita', 'Ștei', 'Aleșd', 'Săcueni', 'Valea lui Mihai'],
  'Bistrița-Năsăud': ['Bistrița', 'Năsăud', 'Beclean', 'Sângeorz-Băi'],
  'Botoșani': ['Botoșani', 'Dorohoi', 'Darabani', 'Săveni', 'Bucecea', 'Flămânzi', 'Ștefănești'],
  'Brăila': ['Brăila', 'Ianca', 'Însurăței', 'Făurei'],
  'Brașov': ['Brașov', 'Făgăraș', 'Săcele', 'Codlea', 'Râșnov', 'Predeal', 'Zărnești', 'Victoria', 'Ghimbav', 'Rupea'],
  'București': ['Sector 1', 'Sector 2', 'Sector 3', 'Sector 4', 'Sector 5', 'Sector 6'],
  'Buzău': ['Buzău', 'Râmnicu Sărat', 'Pogoanele', 'Nehoiu', 'Pătârlagele', 'Mizil'],
  'Caraș-Severin': ['Reșița', 'Caransebeș', 'Bocșa', 'Moldova Nouă', 'Oravița', 'Anina', 'Băile Herculane'],
  'Călărași': ['Călărași', 'Oltenița', 'Lehliu-Gară', 'Budești', 'Fundulea'],
  'Cluj': ['Cluj-Napoca', 'Turda', 'Câmpia Turzii', 'Dej', 'Gherla', 'Huedin'],
  'Constanța': ['Constanța', 'Mangalia', 'Medgidia', 'Cernavodă', 'Năvodari', 'Eforie', 'Negru Vodă', 'Ovidiu', 'Techirghiol'],
  'Covasna': ['Sfântu Gheorghe', 'Târgu Secuiesc', 'Covasna', 'Baraolt', 'Întorsura Buzăului'],
  'Dâmbovița': ['Târgoviște', 'Moreni', 'Pucioasa', 'Găești', 'Fieni', 'Răcari', 'Titu'],
  'Dolj': ['Craiova', 'Băilești', 'Calafat', 'Dăbuleni', 'Filiași', 'Segarcea'],
  'Galați': ['Galați', 'Tecuci', 'Târgu Bujor', 'Berești'],
  'Giurgiu': ['Giurgiu', 'Bolintin-Vale', 'Mihăilești'],
  'Gorj': ['Târgu Jiu', 'Rovinari', 'Motru', 'Bumbeșești-Jiu', 'Novaci', 'Târgu Cărbunești', 'Turceni'],
  'Harghita': ['Miercurea Ciuc', 'Odorheiu Secuiesc', 'Gheorgheni', 'Toplița', 'Cristuru Secuiesc', 'Borsec', 'Bălan'],
  'Hunedoara': ['Deva', 'Hunedoara', 'Petroșani', 'Orăștie', 'Brad', 'Simeria', 'Vulcan', 'Lupeni', 'Petrila', 'Uricani'],
  'Ialomița': ['Slobozia', 'Fetești', 'Urziceni', 'Amara', 'Căzănești', 'Fierbinți-Târg', 'Țăndărei'],
  'Iași': ['Iași', 'Pașcani', 'Hârlău', 'Târgu Frumos', 'Podu Iloaiei'],
  'Ilfov': ['Voluntari', 'Popești-Leordeni', 'Pantelimon', 'Buftea', 'Otopeni', 'Măgurele', 'Chitila', 'Bragadiru', 'Tunari'],
  'Maramureș': ['Baia Mare', 'Sighetu Marmației', 'Borșa', 'Câmpulung la Tisa', 'Seini', 'Târgu Lăpuș', 'Vișeu de Sus'],
  'Mehedinți': ['Drobeta-Turnu Severin', 'Orșova', 'Strehaia', 'Vânju Mare'],
  'Mureș': ['Târgu Mureș', 'Reghin', 'Sighișoara', 'Târnăveni', 'Luduș', 'Iernut', 'Sovata'],
  'Neamț': ['Piatra Neamț', 'Roman', 'Bicaz', 'Roznov', 'Târgu Neamț'],
  'Olt': ['Slatina', 'Caracal', 'Corabia', 'Balș', 'Drăgănești-Olt', 'Scornicești'],
  'Prahova': ['Ploiești', 'Câmpina', 'Sinaia', 'Azuga', 'Băicoi', 'Boldești-Scăeni', 'Breaza', 'Bușteni', 'Comarnic', 'Urlați', 'Vălenii de Munte'],
  'Satu Mare': ['Satu Mare', 'Carei', 'Negrești-Oaș', 'Tășnad'],
  'Sălaj': ['Zalău', 'Șimleu Silvaniei', 'Cehu Silvaniei', 'Jibou'],
  'Sibiu': ['Sibiu', 'Mediaș', 'Cisnădie', 'Agnita', 'Avrig', 'Copșa Mică', 'Dumbrăveni', 'Miercurea Sibiului', 'Ocna Sibiului', 'Tălmaciu'],
  'Suceava': ['Suceava', 'Fălticeni', 'Câmpulung Moldovenesc', 'Gura Humorului', 'Rădăuți', 'Vatra Dornei', 'Siret', 'Solca'],
  'Teleorman': ['Alexandria', 'Roșiorii de Vede', 'Turnu Măgurele', 'Zimnicea', 'Videle'],
  'Timiș': ['Timișoara', 'Lugoj', 'Sânnicolau Mare', 'Buziaș', 'Deta', 'Jimbolia', 'Recaș'],
  'Tulcea': ['Tulcea', 'Babadag', 'Isaccea', 'Măcin', 'Sulina'],
  'Vaslui': ['Vaslui', 'Bârlad', 'Huși', 'Negrești'],
  'Vâlcea': ['Râmnicu Vâlcea', 'Drăgășani', 'Băile Govora', 'Băile Olănești', 'Brezoi', 'Călimănești', 'Horezu', 'Ocnele Mari'],
  'Vrancea': ['Focșani', 'Adjud', 'Mărășești', 'Panciu'],
}
